CREATE TABLE books (
    `id` LONGTEXT NOT NULL,
    `ourn` LONGTEXT,
    `isbn` bigint,
    `last_modified_time` DATETIME,
    `issued` DATETIME,
    `format` TEXT,
    `content_format` TEXT,
    `authors` JSON,
    `publishers` JSON,
    `language` TEXT,
    `title` LONGTEXT,
    `description` LONGTEXT,
    `url` LONGTEXT,
    `web_url` TEXT,
    `virtual_pages` INTEGER,
    `timestamp` DATETIME,
    `average_rating` INTEGER,
    `number_of_followers` INTEGER,
    `number_of_items` INTEGER,
    `number_of_reviews` INTEGER,
    `popularity` INTEGER,
    `report_score` INTEGER,
    `cover_url` LONGTEXT,
    `date_added` DATETIME,
    `topics` JSON,
    `topics_payload` JSON,
    `minutes_required` INTEGER
)
